// Copyright 2025-present 650 Industries. All rights reserved.

import Foundation

/**
 A `Sendable` snapshot of a single HTTP request observed by `NetworkRequestURLProtocol`.

 The shape is intentionally close to `URLSessionTaskTransactionMetrics` so we can plumb individual
 timing phases into telemetry later without redesigning the type. Until the metrics pipeline is
 wired up, this is what gets handed to `NetworkRequestObserverDelegate` callers.

 The URL is recorded verbatim — including the query string — because callers asked for it. Any
 redaction (tokens in query parameters, auth headers, etc.) is the responsibility of whatever
 downstream layer converts these snapshots into stored metrics.
 */
public struct NetworkRequest: Sendable, Equatable, Identifiable {
  /** Stable identifier for this observation. Generated by the protocol class. */
  public let id: UUID

  /** Request URL as supplied to `URLSession`. May include query parameters and fragments. */
  public let url: URL

  /** HTTP method (`GET`, `POST`, …). Defaults to `GET` if `URLRequest.httpMethod` was nil. */
  public let method: String

  /** Response status code, or `nil` if the request failed before headers were received. */
  public let statusCode: Int?

  /**
   Negotiated wire protocol — `http/1.1`, `h2`, `h3` — as reported by
   `URLSessionTaskTransactionMetrics.networkProtocolName`. `nil` for cache hits or when the OS
   didn't report one.
   */
  public let networkProtocol: String?

  /** Number of bytes sent on the wire for the request (headers + body). */
  public let requestBytesSent: Int64?

  /** Number of bytes received on the wire for the response (headers + body). */
  public let responseBytesReceived: Int64?

  /** Whether the response was served from a local cache. */
  public let wasCached: Bool

  /** Phase-by-phase timings pulled from the most recent (post-redirect) transaction. */
  public let timings: Timings

  /**
   Short human-readable error description if the task completed with an error. We keep this as a
   string rather than carrying `NSError` so the type stays `Sendable` and serializable.
   */
  public let errorDescription: String?

  public struct Timings: Sendable, Equatable {
    /** When the task was started (`URLSessionTaskTransactionMetrics.fetchStartDate`). */
    public let fetchStart: Date?

    /** When DNS resolution began. `nil` if the host was resolved from cache or the connection was reused. */
    public let domainLookupStart: Date?
    public let domainLookupEnd: Date?

    /** When the TCP connection began. `nil` if a connection was reused. */
    public let connectStart: Date?
    public let connectEnd: Date?

    /** TLS handshake window. `nil` for cleartext or reused connections. */
    public let secureConnectionStart: Date?
    public let secureConnectionEnd: Date?

    /** When the request line began being sent. */
    public let requestStart: Date?
    public let requestEnd: Date?

    /** When the first byte of the response arrived (TTFB). */
    public let responseStart: Date?
    public let responseEnd: Date?

    /**
     Total wall-clock duration of the task. Convenience: callers don't have to subtract
     `fetchStart` from `responseEnd` themselves, and we can populate this even when the
     individual phases are `nil` (cache hits, errors before headers).
     */
    public let totalDuration: TimeInterval
  }
}

extension NetworkRequest {
  /**
   Builds a snapshot from the data we have at task completion. The metrics argument may be `nil`
   for cache-only responses or in tests; in that case, callers fall back to wall-clock timestamps
   on the request/response pair.
   */
  static func from(
    id: UUID,
    request: URLRequest,
    response: HTTPURLResponse?,
    task: URLSessionTask?,
    metrics: URLSessionTaskMetrics?,
    fallbackStart: Date,
    fallbackEnd: Date,
    error: Error?
  ) -> NetworkRequest {
    let url = request.url ?? URL(string: "about:blank")!
    let method = request.httpMethod ?? "GET"

    // We use the last transaction so that redirects don't drop us back to the first hop. If a
    // future need arises to surface per-hop timing, expose `metrics.transactionMetrics` here.
    let transaction = metrics?.transactionMetrics.last

    let timings = NetworkRequest.Timings(
      fetchStart: transaction?.fetchStartDate ?? fallbackStart,
      domainLookupStart: transaction?.domainLookupStartDate,
      domainLookupEnd: transaction?.domainLookupEndDate,
      connectStart: transaction?.connectStartDate,
      connectEnd: transaction?.connectEndDate,
      secureConnectionStart: transaction?.secureConnectionStartDate,
      secureConnectionEnd: transaction?.secureConnectionEndDate,
      requestStart: transaction?.requestStartDate,
      requestEnd: transaction?.requestEndDate,
      responseStart: transaction?.responseStartDate,
      responseEnd: transaction?.responseEndDate ?? fallbackEnd,
      totalDuration: metrics?.taskInterval.duration ?? fallbackEnd.timeIntervalSince(fallbackStart)
    )

    let wasCached: Bool = {
      guard let transaction else {
        return false
      }
      return transaction.resourceFetchType == .localCache
    }()

    // Prefer the transaction's header+body split when metrics arrived, fall back to the task's
    // total byte counters otherwise — those are populated even when the inner session's metrics
    // callback never fires (a real failure mode for `URLProtocol`-wrapped tasks).
    let requestBytesSent: Int64? = {
      if let transaction {
        return transaction.countOfRequestHeaderBytesSent + transaction.countOfRequestBodyBytesSent
      }
      return task?.countOfBytesSent
    }()
    let responseBytesReceived: Int64? = {
      if let transaction {
        return transaction.countOfResponseHeaderBytesReceived + transaction.countOfResponseBodyBytesReceived
      }
      return task?.countOfBytesReceived
    }()

    return NetworkRequest(
      id: id,
      url: url,
      method: method,
      statusCode: response?.statusCode,
      networkProtocol: transaction?.networkProtocolName,
      requestBytesSent: requestBytesSent,
      responseBytesReceived: responseBytesReceived,
      wasCached: wasCached,
      timings: timings,
      errorDescription: error.map { ($0 as NSError).localizedDescription }
    )
  }
}
